services:

  caddy:
    image: caddy:2.5.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./archive:/etc/caddy/roots/archive

  archiver:
    image: osem-archiver:latest
    restart: on-failure
    volumes:
      - ./archive:/archive
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - ./dumps:/dumps
      - ./exports:/exports
      - ./scripts/mongodb/aggregations.js:/functions/aggregations.js
      - ./scripts/mongodb/osem_admin.sh:/docker-entrypoint-initdb.d/osem_admin.sh
      - ./scripts/mongodb/osem_seed_import.sh:/docker-entrypoint-initdb.d/osem_seed_import.sh
      - ./scripts/mongodb/osem_seed_pipelines.sh:/docker-entrypoint-initdb.d/osem_seed_pipelines.sh

volumes:
  caddy_data:
  caddy_config: